name: "Test"

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Install cachix
        uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install tarball+https://install.devenv.sh/latest
      - name: Setup nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Setup go cache
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run pre-commit hooks
        run: |
          devenv shell -- pre-commit run --all-files
      - name: Build
        run: |
          devenv shell -- go build
