name: "Test"

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Install cachix
        uses: cachix/cachix-action@v12
        with:
          name: devenv
      - name: Run devenv tests
        run: nix develop --quiet --impure --command bash -c "devenv test"
      - name: Build
        run: |
          devenv shell -- go build
