name: Linters
on:
  push:
    branches: [main]
  pull_request:
jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      - uses: actions/setup-go@v7
        with:
          go-version: '1.26.5'
      - uses: golangci/golangci-lint-action@v9
      - uses: j178/prek-action@v3.0.0
        with:
          extra-args: --all-files --skip no-commit-to-branch --skip "golangci-lint-full" --skip "golangci-lint-fmt" --skip "golangci-lint-config-verify"
