on:
  pull_request:
  push:
    branches: [main]
jobs:
  lints:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Build
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.26.x'
      - run: go test -v ./...
