on:
  pull_request:
  push:
    branches: [main]
jobs:
  lints:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Build
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.26.x'
      - run: go test -v ./...
